### ISSUE TITLE
adding import for reduce

### ISSUE THREAD

**Issue by alinafe82** [UWPCE-PythonCert/IntroPython-2017#113]
https://uwpce-pythoncert.github.io/PythonCertDevel/modules/Testing.html#unit-testing
**from functools import reduce** required to run below code in document

```
# in test_my_mod.py
import unittest
from my_mod import my_func

class MyFuncTestCase(unittest.TestCase):
    def test_my_func(self):
        test_vals = (2, 3)
        expected = reduce(lambda x, y: x * y, test_vals)
        actual = my_func(*test_vals)
        self.assertEquals(expected, actual)


if __name__ == '__main__':
    unittest.main()
```

**Comment by PythonCHB** [comment]
Thanks!

Apparently we hadn't tested that code since py2.7. `reduce` used to be a builtin.

I've updated it -- quite a bit actually.

And removed reduce altogether -- it really wasn't important for that example.

Thanks!
